/*BANCO DE DADOS PEDIDOS CLIENTE

CLIENTE SOLICITOU UM ORÇAMENTO PARA CRIAÇÃO DE VENDAS E SUA LOJA.

PEDIU QUE **** CLIENTES **** POSUISSEM NO REGISTRO NOME, CPF, RG E TELEFONE.
NOS **** PEDIDOS **** DATA PEDIDO, DATA ENVIO PEDIDO.
EM **** ITENS PEDIDO ***** QUANTIDADE E UNIDADE.
EM **** PRODUTOS **** PRECO UNITARIO, NOME PRODUTO  
E **** FORNECEDORES **** RAZAO SOCIAL, CNPJ, TELEFONE
*/


CREATE DATABASE PEDIDOS_CLIENTES

USE PEDIDOS_CLIENTES

CREATE TABLE TB_CLIENTE
(
	CODCLIENTE INT IDENTITY (1,1) NOT NULL,
	CPF VARCHAR(11) NOT NULL,
	RG  VARCHAR(15),
	TELEFONE VARCHAR(10),
)

ALTER TABLE TB_CLIENTE ADD
NOME VARCHAR(50) NOT NULL
CONSTRAINT PK_TB_CLIENTE_CODCLIENTE PRIMARY KEY(CODCLIENTE)

CREATE TABLE  TB_PEDIDOS
(
	NUMPEDIDO INT IDENTITY (1,1) NOT NULL,
	DATAPEDIDO DATETIME DEFAULT GETDATE(),
	DATAENVIOPEDIDO DATETIME DEFAULT GETDATE(),
	CODCLIENTE INT NOT NULL,
)

ALTER TABLE TB_PEDIDOS ADD
CONSTRAINT PK_TB_PEDIDOS_CODPEDIDO PRIMARY KEY (NUMPEDIDO),
CONSTRAINT FK_TB_PEDIDO_CODCLIENTE FOREIGN KEY (CODCLIENTE) REFERENCES TB_CLIENTE(CODCLIENTE)

CREATE TABLE TB_ITENS_PEDIDO
(
	CODITENS INT IDENTITY (1,1) NOT NULL,
	QUANTIDADE VARCHAR(50) NOT NULL,
	UNIDADE INT NOT NULL,
	NUMPEDIDO INT NOT NULL,
	IDPRODUTO INT NOT NULL
)

ALTER TABLE TB_ITENS_PEDIDO ADD
CONSTRAINT PK_TB_ITENS_PEDIDO_CODITENS PRIMARY KEY (CODITENS),
CONSTRAINT CK_TB_ITENS_PEDIDO_QUANTIDADE CHECK (QUANTIDADE >= 0),
CONSTRAINT FK_TB_ITENS_PEDIDO_NUMPEDIDO FOREIGN KEY (NUMPEDIDO) REFERENCES TB_PEDIDOS(NUMPEDIDO),
CONSTRAINT FK_TB_ITENS_PEDIDO_IDPRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES TB_PRODUTOS(IDPRODUTO)

CREATE TABLE TB_PRODUTOS
(
	IDPRODUTO INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	PRECO_UNITARIO NUMERIC(10,2) CHECK (PRECO_UNITARIO >= 0)NOT NULL,
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	IDFORN INT NOT NULL
)
ALTER TABLE TB_PRODUTOS ADD
CONSTRAINT FK_TB_PRODUTOS_IDFORN FOREIGN KEY (IDFORN) REFERENCES TB_FORNECEDORES(IDFORN)

CREATE TABLE TB_FORNECEDORES
(
	IDFORN INT IDENTITY PRIMARY KEY NOT NULL,
	RAZAOSOCIAL VARCHAR(50) NOT NULL,
	CNPJ VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(10),
)


INSERT INTO TB_CLIENTE (CPF,RG,TELEFONE,NOME)
VALUES
('11111111111','','30562523','LUCAS'),
('22222222222','12346','','SAMANTA'),
('33333333333','1234666','50231324','ELVIS')

SELECT * FROM TB_CLIENTE -------CONSULTA-------

INSERT INTO TB_PEDIDOS (DATAPEDIDO,DATAENVIOPEDIDO,CODCLIENTE)
VALUES
('1900/01/01','1900/01/01',1),
('2000/01/01','1900/20/02',2),
('1200/20/01','23/05/2024',3)

SELECT * FROM TB_PEDIDOS -------CONSULTA-------
SELECT *,CONVERT(VARCHAR(10),DATAENVIOPEDIDO,103) AS 'DATA ENVIO PEDIDO' FROM TB_CLIENTE CLI JOIN TB_PEDIDOS PE ON CLI.CODCLIENTE=PE.CODCLIENTE -------CONSULTA-------

INSERT INTO TB_ITENS_PEDIDO (QUANTIDADE,UNIDADE,NUMPEDIDO,IDPRODUTO)
VALUES
('50',25,15,1),
('30',25,18,2),
('1',2,22,3)

SELECT * FROM TB_ITENS_PEDIDO -------CONSULTA-------
SELECT * FROM TB_CLIENTE CLI JOIN TB_PEDIDOS PE ON CLI.CODCLIENTE=PE.CODCLIENTE
LEFT JOIN TB_ITENS_PEDIDO IT ON IT.NUMPEDIDO=PE.NUMPEDIDO -------CONSULTA-------


INSERT INTO TB_PRODUTOS (PRECO_UNITARIO,NOME_PRODUTO,IDFORN)
VALUES
(1500.02,'CHUVEIRO',1),
(1000.50,'VIDEO GAME',2),
(5.00,'DOCE DE LEITE',3)

SELECT * FROM TB_PRODUTOS -------CONSULTA-------
SELECT * FROM TB_CLIENTE CLI JOIN TB_PEDIDOS PE ON CLI.CODCLIENTE=PE.CODCLIENTE
LEFT JOIN TB_ITENS_PEDIDO IT ON IT.NUMPEDIDO=PE.NUMPEDIDO
LEFT JOIN TB_PRODUTOS PR ON PR.IDPRODUTO=IT.IDPRODUTO -------CONSULTA-------

INSERT INTO TB_FORNECEDORES (RAZAOSOCIAL,CNPJ,TELEFONE)
VALUES
('EMPRESAS LTDA','111111111',''),
('CONFEITARIA LTDA','22222222','5505056'),
('DOCES LTDA','222222222','')

SELECT * FROM TB_FORNECEDORES -------CONSULTA-------
SELECT * FROM TB_CLIENTE CLI JOIN TB_PEDIDOS PE ON CLI.CODCLIENTE=PE.CODCLIENTE
LEFT JOIN TB_ITENS_PEDIDO IT ON IT.NUMPEDIDO=PE.NUMPEDIDO
LEFT JOIN TB_PRODUTOS PR ON PR.IDPRODUTO=IT.IDPRODUTO
LEFT JOIN TB_FORNECEDORES FO ON FO.IDFORN=PR.IDFORN -------CONSULTA-------














